spring.application.name=ai_pro
spring.datasource.url=jdbc:h2:mem:urlshortener;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
app.base-url=http://localhost:8080
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
